name: build

permissions: 
  contents: write

on:
  push:
    branches:
      - '**'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js 18
      uses: actions/setup-node@v6
      with:
        node-version: 18

    - name: Prepare dependencies
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build

    - name: Checkout GitHub Pages Branch
      if: success() && github.ref == 'refs/heads/main'
      uses: actions/checkout@v5
      with:
        ref: gh-pages
        path: temp
        
    - name: prepare commit
      if: success() && github.ref == 'refs/heads/main'
      run: |
        cd temp
        rm -rf *
        cp -r ../dist/. .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        if ! git diff-index --quiet HEAD; then
            echo "changes_exist=true" >> $GITHUB_ENV
        fi

    - name: deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main' && env.changes_exist == 'true'
      run: |
        git commit -m "deploy version ${{ github.sha }}"
        git push
