name: build

on:
  push:
    branches:
      - '**'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Lint
      run: |
        yarn
        yarn lint

    - name: Build
      run: yarn build

    - name: Checkout GitHub Pages Branch
      if: success() && github.ref == 'refs/heads/main'
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: temp
    - name: deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      run: |
        cd temp
        rm -rf *
        cp -r ../dist/. .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
